server {
    listen 80;
    server_name your_domain.com www.your_domain.com; # REPLACE WITH YOUR DOMAIN OR IP

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        root /home/ubuntu/Shivank-Kirana-Store;
    }

    location /media/ {
        root /home/ubuntu/Shivank-Kirana-Store;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/Shivank-Kirana-Store/app.sock;
    }
}
