server {
    listen 80;
    server_name _; # Change this to your actual domain name e.g. shivankkirana.com www.shivankkirana.com;

    location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
    }
    
    # Serve static files directly via Nginx
    location /static/ {
        root /var/www/shivank_kirana;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # Serve media files directly via Nginx
    location /media/ {
        root /var/www/shivank_kirana;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # Proxy all other requests to Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/shivank_kirana/gunicorn.sock;
    }
}
